### ISSUE TITLE
Definição do site

### ISSUE THREAD

**Issue by klmurussi** [Interacao-Humano-Computador/2021.2-Prefeitura-de-Passo-Fundo#1]
Cada integrante deve escolher um site e avaliar
- [x] Kathlyn - Site do Capes Periódicos : https://www-periodicos-capes-gov-br.ezl.periodicos.capes.gov.br/index.php?
- [x] Lorenzo - https://home.universidadepatativa.com.br/
- [x] Kayro - Prefeitura de Passo Fundo - RS :   http://www.pmpf.rs.gov.br/ 
- [x] Adrian (@SwampTG) - [MPU ]( http://www.mpu.mp.br/)
- [x] Magno (@magnluiz ) - [UNB ](https://www.unb.br/)

Requisito pra ser aceito:
- [x] escolha do site

**Comment by kayrocesar** [comment]
Foi definido em reunião e com a maioria dos votos o site da Prefeitura De Passo Fundo-RS
