### ISSUE TITLE
Criar templates de Issue, PR, e reunião

### ISSUE THREAD

**Issue by klmurussi** [Interacao-Humano-Computador/2021.2-Prefeitura-de-Passo-Fundo#2]
Para melhor organização na hora de criar issues, PRs, e controle das reuniões, é bom criar templates

- [x] Template Issue
- [x] Template PR
- [x] Template Meeting

**Comment by SwampTG** [comment]
Se quiserem tenho os templates de Issue e Pr que fiz em outra disciplina, se acharem eles bons
[git.zip](https://github.com/Interacao-Humano-Computador/2021.2-Grupo-02/files/7998200/git.zip)
.

**Comment by kayrocesar** [comment]
@SwampTG  Pode ser

**Comment by kayrocesar** [comment]
> Se quiserem tenho os templates de Issue e Pr que fiz em outra disciplina, se acharem eles bons [git.zip](https://github.com/Interacao-Humano-Computador/2021.2-Grupo-02/files/7998200/git.zip) .

Boa,por mim está otimo.
